version: "{branch} {build}"

build:
  verbosity: detailed

before_build:
  - SET PATH=%JAVA_HOME%\bin;%PATH%\
  - ps: Install-Module DockerMsftProvider -Force
  - ps: Install-Package Docker -ProviderName DockerMsftProvider -Force

build_script:
- gradlew-public.bat -b build-public.gradle clean build --info --no-daemon

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk11

matrix:
  fast_finish: false